/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseIcon: typeof import('./src/components/base/BaseIcon.vue')['default']
    Card: typeof import('./src/components/base/Card.vue')['default']
    Loader: typeof import('./src/components/Loader.vue')['default']
    Picker: typeof import('./src/components/forms/picker.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
