[workspace]
members = ["services/auth-service", "services/hrms-service", "gate_way"]
resolver = "2"

[dependencies]
actix-web = "4.9.0"
actix-cors = "0.7.0"
awc = { version = "3.5.1", features = ["openssl"] }
futures = "0.3.30"
sqlx = { version = "0.8.1", features = [
  "postgres",
  "macros",
  "runtime-tokio",
  "tls-native-tls",
  "uuid",
  "chrono"
] }
serde = { version = "1.0.209", features = ["derive"] }
serde_json = "1.0.120"
sha2 = "0.10.8"
rand = "0.8.5"
jsonwebtoken = "9.3"
redis = "0.26.1"
uuid = { version = "1.10.0", features = ["serde", "v4"] }
chrono = { version = "0.4.38", features = ["serde"] }
