[package]
name = "c3k-common"
version = "0.1.0"
edition = "2021"
authors = ["H.Muhammad Kamran"]

[dependencies]
futures = "0.3.30"
sqlx = { version = "0.8.0", features = [
    "postgres",
    "macros",
    "runtime-tokio",
    "tls-native-tls",
    "uuid",
] }
redis = "0.26.0"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"