[package]
name = "c3k-gate-way"
version = "0.1.0"
edition = "2021"
authors = ["H.Muhammad Kamran"]

[dependencies]
c3k-common = { path = "../services/common" }
actix-web = "4.9.0"
actix-cors = "0.7.0"
awc = { version = "3.5.1", features = ["openssl"] }
