/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ChildDisplay: typeof import('./src/components/base/ChildDisplay.vue')['default']
    Moduleform: typeof import('./src/components/forms/moduleform.vue')['default']
    Modules: typeof import('./src/components/base/modules.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
